/**
  **************************
  UPDATE 7.1
  *************************
 */
ALTER TABLE `ACCOUNTSTACK` ADD `TAX_VALUE` double precision NULL AFTER `ACCOUNT_TAX_TYPE`;
ALTER TABLE `ACCOUNTSTACK` CHANGE `ACCOUNT_TAX_TYPE` `ACCOUNT_DEBIT_TAX_TYPE` VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE `ACCOUNTSTACK` ADD `ACCOUNT_CREDIT_TAX_TYPE` VARCHAR(255) NULL AFTER `ACCOUNT_DEBIT_TAX_TYPE`; 